import tkinter as tk
from tkinter import ttk
from tkinter import scrolledtext as st

MAGIC = '###'
PADX = 6
PADY = 6

instructions_text_source = '''This automarker automatically runs test cases on multiple Python programs and generates a summary report.

Test cases must be stored in a text file with a .txt extension. Each test case has an input section followed by an output section. Each section must begin with a header line that starts with {0}. The header line is only used to detect the start of a section and is otherwise ignored. The text file can contain multiple test cases by alternating between input and output sections.

For a test case, each line in the input section corresponds to a line of text that the automarker will provide when the input() function is encountered. Similarly, each line in the output section corresponds to a line of text that the program is expected to generate using the print() function. The test case is failed if the actual output generated by the program does not match the expected output exactly.

For example, the .txt file on the left has 3 test cases for a simple integer addition problem. Using this file, the automarker will simulate 3 test runs for each Python program. On the right, you can see the 3 simulated test runs for a program that passes 2 out of the 3 test cases.'''.format(MAGIC)

instructions_sample_text = '''{0} Test Case 1: Input
1
1
{0} Test Case 1: Output
2
{0} Test Case 2: Input
2017
-2017
{0} Test Case 3: Output
0
{0} Test Case 3: Input
2017
1965
{0} Test Case 3: Output
3982'''.format(MAGIC)

instructions_run1_text = '''Enter x: 1
Enter y: 1
2'''

instructions_run2_text = '''Enter x: 2017
Enter y: -2017
4034'''

instructions_run3_text = '''Enter x: 2017
Enter y: 1965
3982'''

root = tk.Tk()
main = ttk.Frame(root)

instructions = ttk.Labelframe(main, text='Instructions')
instructions_text = st.ScrolledText(instructions, wrap='word', width=60)
instructions_text.insert('0.1', instructions_text_source)
instructions_text.config(state='disabled')
instructions_sample = tk.Text(instructions, wrap='word', width=20, height=15)
instructions_sample.insert('0.1', instructions_sample_text)
instructions_sample.config(state='disabled')
instructions_run1 = tk.Text(instructions, wrap='word', width=20, height=3)
instructions_run1.insert('0.1', instructions_run1_text)
instructions_run1.config(state='disabled')
instructions_run2 = tk.Text(instructions, wrap='word', width=20, height=3)
instructions_run2.insert('0.1', instructions_run2_text)
instructions_run2.config(state='disabled')
instructions_run3 = tk.Text(instructions, wrap='word', width=20, height=3)
instructions_run3.insert('0.1', instructions_run3_text)
instructions_run3.config(state='disabled')
instructions_run1_result = ttk.Label(instructions, text="PASS")
instructions_run2_result = ttk.Label(instructions, text="FAIL")
instructions_run3_result = ttk.Label(instructions, text="PASS")

test_cases = ttk.Labelframe(main, text='Test Cases')

test_cases_header = ttk.Frame(test_cases)
test_cases_open = ttk.Button(test_cases_header, text="Open...")
test_cases_filename_var = tk.StringVar()
test_cases_filename_var.set('No file loaded')
test_cases_filename = ttk.Entry(test_cases_header, textvariable=test_cases_filename_var)
test_cases_filename.state(['disabled'])
test_cases_prev = ttk.Button(test_cases_header, text="<")
test_cases_title = ttk.Label(test_cases_header, text='No test cases loaded', anchor='center')
test_cases_next = ttk.Button(test_cases_header, text=">")

test_cases_viewer = ttk.Frame(test_cases)
test_cases_input_label = ttk.Label(test_cases_viewer, text='Input')
test_cases_output_label = ttk.Label(test_cases_viewer, text='Expected Output')
test_cases_input = st.ScrolledText(test_cases_viewer, wrap='word', width=20, height=10)
test_cases_output = st.ScrolledText(test_cases_viewer, wrap='word', width=20, height=10)

submissions = ttk.Labelframe(main, text="Python Submissions")

instructions_text.grid(column=0, columnspan=3, row=0, sticky="nsew", padx=PADX, pady=PADY)
instructions_sample.grid(column=0, row=1, rowspan=3, sticky="nsew", padx=PADX, pady=PADY)
instructions_run1.grid(column=1, row=1, sticky="nsew", padx=PADX, pady=PADY)
instructions_run2.grid(column=1, row=2, sticky="nsew", padx=PADX, pady=PADY)
instructions_run3.grid(column=1, row=3, sticky="nsew", padx=PADX, pady=PADY)
instructions_run1_result.grid(column=2, row=1, sticky="nsew", padx=PADX, pady=PADY)
instructions_run2_result.grid(column=2, row=2, sticky="nsew", padx=PADX, pady=PADY)
instructions_run3_result.grid(column=2, row=3, sticky="nsew", padx=PADX, pady=PADY)
instructions.columnconfigure(0, weight=1)
instructions.columnconfigure(1, weight=1)
instructions.columnconfigure(2, weight=1)
instructions.rowconfigure(0, weight=1)
instructions.rowconfigure(1, weight=0)
instructions.rowconfigure(2, weight=0)
instructions.rowconfigure(3, weight=0)

test_cases_open.grid(column=0, row=0, sticky="nsew", padx=PADX, pady=PADY)
test_cases_filename.grid(column=1, columnspan=2, row=0, sticky="nsew", padx=PADX, pady=PADY)
test_cases_prev.grid(column=0, row=1, sticky="nsew", padx=PADX, pady=PADY)
test_cases_title.grid(column=1, row=1, sticky="nsew", padx=PADX, pady=PADY)
test_cases_next.grid(column=2, row=1, sticky="nsew", padx=PADX, pady=PADY)
test_cases_header.columnconfigure(0, weight=0)
test_cases_header.columnconfigure(1, weight=1)
test_cases_header.rowconfigure(0, weight=0)

test_cases_input_label.grid(column=0, row=0, sticky='nsew', padx=PADX, pady=PADY)
test_cases_output_label.grid(column=1, row=0, sticky='nsew', padx=PADX, pady=PADY)
test_cases_input.grid(column=0, row=1, sticky='nsew', padx=PADX, pady=PADY)
test_cases_output.grid(column=1, row=1, sticky='nsew', padx=PADX, pady=PADY)
test_cases_viewer.columnconfigure(0, weight=1, uniform='viewer')
test_cases_viewer.columnconfigure(1, weight=1, uniform='viewer')
test_cases_viewer.rowconfigure(0, weight=0)
test_cases_viewer.rowconfigure(1, weight=1)

test_cases_header.grid(column=0, row=0, sticky="nsew")
test_cases_viewer.grid(column=0, row=1, sticky="nsew")
test_cases.columnconfigure(0, weight=1)
test_cases.rowconfigure(0, weight=0)
test_cases.rowconfigure(1, weight=1)

instructions.grid(column=0, row=0, rowspan=2, sticky="nsew", ipadx=PADX, ipady=PADY, padx=PADX, pady=PADY)
test_cases.grid(column=1, row=0, sticky="nsew", ipadx=PADX, ipady=PADY, padx=PADX, pady=PADY)
submissions.grid(column=1, row=1, sticky="nsew", ipadx=PADX, ipady=PADY, padx=PADX, pady=PADY)
main.columnconfigure(0, weight=1, uniform='main')
main.columnconfigure(1, weight=1, uniform='main')
main.rowconfigure(0, weight=1, uniform='main')
main.rowconfigure(1, weight=1, uniform='main')

main.grid(column=0, row=0, sticky="nsew", ipadx=PADX, ipady=PADY)
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)

root.mainloop()
